name:   'The Algo Engineer'
url:    'http://thealgoengineer.com'
author: "Aidan O'Mahony"

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
pygments: false
markdown: 'kramdown'
timezone: 'Australia/Sydney'
